Ep5cu1 luis erp
Roberto-Ruiz-Obregon/AdminWebApp pull request #14
Opened 2023-04-01 01:27 UTC by Luis-ERP

2023-04-01 20:36 UTC, Leonardo812 commented on src/styles/CourseCard.css
Podrían explicarme que hace la línea position: absolute y por qué ya no es necesaria

2023-04-01 23:52 UTC, FerT99 commented on src/screens/EditProgram.js
> +            FireSucess('Curso mofificado con exito.');
curso eliminado*

2023-04-01 23:54 UTC, FerT99 commented on src/screens/EditProgram.js
> +
igual, creo que es necesario vaciar el form cuando ya se crea el curso, o ya se hace automáticamente?

2023-04-01 23:58 UTC, FerT99 approved these changes

2023-04-02 00:35 UTC, CesarJimenezVilleda02 commented on src/screens/EditProgram.js
> +
Aquí estamos hablando de becas no de cursos. En mi humilde opinión, no tiene por qué vaciarse porque en esta página también se crean las becas y si se desea modificar más se va a vaciar la información que se tiene del curso que se está modificando, podrían dejar el curso sin información si se les escapa picarle al botón.

2023-04-02 01:17 UTC, jorgeCastro-CVJJ commented on src/screens/EditProgram.js
> +                        options={['Beca', 'Programa', 'Otro']}
Tengo entendido que como opciones falta agregar 'Apoyo' y 'Evento'

2023-04-02 01:39 UTC, Leonardo812 approved these changes

2023-04-02 08:16 UTC, CesarJimenezVilleda02 requested changes

2023-04-02 08:16 UTC, CesarJimenezVilleda02 commented on src/components/Select.js
> +                        <option key={option} value={option}>
Gracias, no había visto que se me había ido ese detalle

2023-04-02 08:16 UTC, CesarJimenezVilleda02 commented on src/screens/EditProgram.js
> +            FireSucess('Curso mofificado con exito.');
Aquí si se equivocó, pero el cambio sería programa eliminado, estos archivos son de cursos, no programas

2023-04-02 08:16 UTC, CesarJimenezVilleda02 commented on src/screens/Programs.js
> +        .then(data => setPrograms(data));
Falta el catch o cópiate el trycatch que está en topics

2023-04-02 08:16 UTC, CesarJimenezVilleda02 commented on src/screens/verCursos.js
> +        getCourses()
Lo mismo, falta try catch

2023-04-02 08:16 UTC, CesarJimenezVilleda02 commented on src/screens/EditProgram.js
> +                        options={['Beca', 'Programa', 'Otro']}
Aqui habia un error en el back, si se selecciona programa va a fallar por un error de dedo que se te fue en el modelo, ya lo arregle y desplegue los cambios, el enum quedaria como `['Beca', 'Evento', 'Apoyo', 'Programa', 'Otro']`

2023-04-05 23:20 UTC, Luis-ERP commented
Hay un "bug" en el backend cuando se envía una imagen en mal estado truena, probé con las imágenes que usamos en clase de Oscar. Deberíamos atrapar ese error y regresar un 400

2023-04-06 00:37 UTC, CesarJimenezVilleda02 commented
> Hay un "bug" en el backend cuando se envía una imagen en mal estado truena, probé con las imágenes que usamos en clase de Oscar. Deberíamos atrapar ese error y regresar un 400

Creo que es un bug del tamano del archivo, no deberia exceder los 10mb, pero si hay que agregarlo, no entiendo por que no lo atrapa si ya deberia funcionar, este no se puede incrementar porque es el tamano maximo que permite el cache de cloud functions.

Regresando lo revisare @Luis-ERP

2023-04-07 20:27 UTC, jorgeCastro-CVJJ approved these changes

2023-04-10 19:01 UTC, merged