rutas funcionales
Roberto-Ruiz-Obregon/AdminWebApp pull request #2
Opened 2023-03-06 00:06 UTC by FerT99

2023-03-06 03:09 UTC, Luis-ERP commented on src/cursos.js
> +    newCourse: '',
En este caso, no es necesario que newCourse sea un state, ya que no hay otro componente que dependa de esa información. No afecta en nada pero por práctica es mejor que sea el handleSubmit el que lea la información del form. 

Se puede quedar como está pero si recomiendo tomarlo en consideración para la próxima

2023-03-06 03:09 UTC, Luis-ERP commented on src/cursos.js
> +        {this.state.courses.map((course, index) => (
Para que luego sea más fácil darle estilo, este for loop tiene que estar dentro de un contenedor, un div funciona

2023-03-06 03:09 UTC, Luis-ERP commented on src/CourseCard.js
> +import React from 'react';
Para una mejor estructura del proyecto, estaría bien una carpeta dedicada a todos los componentes, otra para las páginas, otra para estilos, una donde estén todas las peticiones a la api, y si se ocupa otra carpeta para utils

2023-03-06 03:09 UTC, Luis-ERP commented on src/dashboard.js
>  // { useState }
Tratemos de no dejar código comentado

2023-03-06 03:23 UTC, CesarJimenezVilleda02 commented
Tambien podriamos seguir la siguiente estructura de archivos:
components/
-------courseCard/
--------------courseCard.jsx (es el componente que ya tienes)
--------------courseCard.styles.scss (podriamos usar scss para agilizar el desarrollo @Luis-ERP ?)

Y los archivos cambialos de .js a .jsx

2023-03-06 03:26 UTC, CesarJimenezVilleda02 requested changes

2023-03-06 03:26 UTC, CesarJimenezVilleda02 commented on src/cursos.js
> -class Cursos extends Component  {
Puede ser mas sencillo si usas hooks y un componente funcional. Los componentes de clase en general ya no se usan mucho. Puedes hacer un hook de useState para cada input que deba ingresar el usuario para completar un curso.

Hook useState:
https://es.reactjs.org/docs/hooks-state.html

2023-03-06 03:26 UTC, CesarJimenezVilleda02 commented on src/cursos.js
> +        {this.state.courses.map((course, index) => (
Por ejemplo, si haces un hook de useState que almacene los cursos como  `const [couses, setCourses] = useState([]);` en esta parte de tu codigo podrias tener algo como `{courses.map((course, index) => (`. Puedes verlo como tener varios estados chiquitos.

2023-03-06 03:26 UTC, CesarJimenezVilleda02 commented on src/style.css
> +  #newCourse, #newCourse_ {
En este caso seria mejor usar una clase porque es algo que estas repitiendo en muchos lados y probablemente usaremos mas adelante, sugiero usar selectores de clase en lugar de id.

2023-03-06 03:26 UTC, CesarJimenezVilleda02 commented on src/sidebar.js
>    const navigate = useNavigate();
Por estandar dejemos esta linea como `function Sidebar() {` y exportemos al final del archivo.

2023-03-06 04:43 UTC, Luis-ERP commented
@CesarJimenezVilleda02 mmm habría que checar si los demás saben escribir sass. Yo creo que para este proyecto no es necesario. Chance perdemos más tiempo haciendo el setup y no es una app grande ni compleja

2023-03-07 15:49 UTC, CesarJimenezVilleda02 requested changes

2023-03-07 15:49 UTC, CesarJimenezVilleda02 commented on src/index.js
> +        <Route path="/verCursos" element={<verCursos />} />
Si las vistas van a tener nombre en mayuscula o camel case hay que mantener la homogeniedad.

2023-03-08 13:25 UTC, felix-rojas requested changes
Sí, hay que dejar todo en camel case mejor

2023-03-08 16:25 UTC, felix-rojas approved these changes
Ahorita le cambiamos a camelCase

2023-03-08 18:18 UTC, CesarJimenezVilleda02 approved these changes

2023-03-08 18:32 UTC, Luis-ERP commented
Se va a hacer merge a master? No deberíamos usar una rama develop?

2023-03-08 18:44 UTC, Luis-ERP commented on src/screens/verCursos.js
> +    <h4 className="inicio_agregar">Inicio / Ver Cursos</h4>
Es esto un placeholder en lo que se implementa, o porqué no tiene return?

2023-03-08 18:49 UTC, FerT99 commented on src/screens/verCursos.js
> +    <h4 className="inicio_agregar">Inicio / Ver Cursos</h4>
todavía no trabajo en esa vista, estoy trabajando en agregar cursos

2023-03-08 18:49 UTC, FerT99 commented on src/screens/verCursos.js
> +    <h4 className="inicio_agregar">Inicio / Ver Cursos</h4>
si quieres esa te la dejo a ti ahorita que haga merge y yo me encargo de la parte visual

2023-03-08 18:51 UTC, Luis-ERP approved these changes

2023-03-08 21:11 UTC, DenisseDB approved these changes

2023-03-08 21:13 UTC, merged