Ep8c1 fer
Roberto-Ruiz-Obregon/AdminWebApp pull request #4
Opened 2023-03-12 00:34 UTC by FerT99

- [ ] Se suben correctamente imagenes al componente de cursos
- [ ] Se agrega descripción, fecha, nombre de curso, modalidad y si es gratuito/de paga

2023-03-12 02:29 UTC, Luis-ERP commented on src/components/CourseCard.js
> +  const [imgSrc] = useState(props.imgSrc);
Para qué usamos un useState para la url de la imágen? en ningún momento se va a modificar

2023-03-12 02:38 UTC, Luis-ERP commented on src/screens/cursos.js
>        {courses.map((course, index) => (
Nadamás checar la identación

2023-03-12 02:38 UTC, Luis-ERP commented on src/styles/style.css
> +    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif
No es necesario poner otra vez los font family si ya se declaran en el body

2023-03-12 09:38 UTC, CesarJimenezVilleda02 requested changes

2023-03-12 09:38 UTC, CesarJimenezVilleda02 commented on src/screens/cursos.js
> +          onChange={handleInputChange}
Podrias modificar cada propiedad usando algo como `onChange={(e) => setState(e.target.value)}` y con eso te aseguras de que el state del hook se actualice cada que interactuan con el input ahorrandote la funcion handleInputChange que con tantos condicionales se vuelve ilegible. La propiedad value se quedaria igual.

2023-03-12 09:38 UTC, CesarJimenezVilleda02 commented on src/screens/cursos.js
>          </label>
Recomendaria hacer un componente para los pares label-input que reciben en los props el state y el useState del hook que les corresponde. Asi podrias modificar todos los inputs desde el mismo lugar.

2023-03-12 09:38 UTC, CesarJimenezVilleda02 commented on src/screens/cursos.js
> +          onChange={handleInputChange}
Como nota adicional, con setState me refiero a las funciones que obtienes de cada hook, no a la funcion setState que se usa en componenes de clase en react. Por ejemplo, setState en mi comentario podria ser el setDate que ya tienes definido, por poner un ejemplo.

2023-03-13 00:57 UTC, FerT99 commented on src/components/CourseCard.js
> +  const [imgSrc] = useState(props.imgSrc);
para cuando agregues un nuevo curso y una nueva imagen es necesario el useState no? o hay forma de reescribir esa parte?

2023-03-13 21:37 UTC, merged