Ep8c2 felix rojas
Roberto-Ruiz-Obregon/AdminWebApp pull request #5
Opened 2023-03-15 18:00 UTC by felix-rojas

Ver cursos establecido como lista, creé un css separado para esta vista puesto que conflictuaba con los css de las tarjetas.
Creo también permite una mejor vista de múltiples elementos

2023-03-15 18:40 UTC, Luis-ERP commented on src/components/CourseCard.js
> +            </div>
Este cambio de identacion es incorrecto

2023-03-15 18:40 UTC, Luis-ERP commented on src/components/CourseList.js
> +    console.log('redireccionar');
usa useNavigate

2023-03-15 18:40 UTC, Luis-ERP commented on src/components/fs_emulator_connect.js
Esto no es un componente. Sugiero que crees un nuevo archivo util o client
Ejemplos:
utils/fs_emulator_connect.js
client/fs_emulator_connect.js

Utils es una carpeta con helper functions, Client es la carpeta donde se van a realizar todas las conexiones a APIs. Decide en qué categoría cae esta función

2023-03-15 18:40 UTC, Luis-ERP commented on src/index.js
> +      <script src="./assets/feather.min.js"></script>
Siento que esto puede ir mejor en el index.html porque es un import de todo el proyecto 'public/index.html'
Que opinan @CesarJimenezVilleda02 @jorgeCastro-CVJJ @DenisseDB ?

2023-03-15 18:40 UTC, Luis-ERP commented on src/screens/verCursos.js
La llamada al back está fuera del scope ahorita? Ya es posible integrarse con el back

2023-03-16 02:03 UTC, alanrazop approved these changes

2023-03-16 05:56 UTC, CesarJimenezVilleda02 requested changes

2023-03-16 05:56 UTC, CesarJimenezVilleda02 commented on src/screens/verCursos.js
> +//   getAllCourses() {
Por que eliminaron esto? No les estaba funcionando la conexion con el back?

2023-03-16 05:56 UTC, CesarJimenezVilleda02 commented on src/index.js
> +      <script src="./assets/feather.min.js"></script>
Mejor com import global. @felix-rojas intenta integrarlo como si fuera global, si te bloqueas mucho resuelve la conversacion y ya lo dejamos asi.

2023-03-16 15:09 UTC, FerT99 commented on src/screens/verCursos.js
> +            <div className='conatiner'>
hay que cuidar dejar el mismo nombre en los classNames porque luego no encontramos las variables

2023-03-16 15:11 UTC, FerT99 commented on package.json
>      "react-feather": "^2.0.10",
hay que definir si usaremos feather icon o react feather para evitar el error de la vez pasada

2023-03-16 15:58 UTC, jorgeCastro-CVJJ approved these changes

2023-03-28 15:14 UTC, felix-rojas commented on package.json
>      "react-feather": "^2.0.10",
react feather es más personalizable y deja menos texto, ya lo quité

2023-03-29 03:21 UTC, Luis-ERP commented
Hay conflictos de merge

2023-03-29 06:57 UTC, CesarJimenezVilleda02 approved these changes
Gracias por el apoyo Felix, me parecen excelentes los estilos que implementaste, solo que con la urgencia de esta PR en particular hubiera preferido que entregaras algo mas rustico antes. Aun asi, gran trabajo.

Ya solo te falta resolver los conflictos de merge.

2023-03-30 00:21 UTC, CesarJimenezVilleda02 requested changes

2023-03-30 00:21 UTC, CesarJimenezVilleda02 commented on src/components/fs_emulator_connect.js
> +const db = getFirestore();
Este archivo no deberia estar en esta carpeta, esto no es un componente.

2023-04-10 19:02 UTC, closed without merging