Ep1cu1 luis erp
Roberto-Ruiz-Obregon/AdminWebApp pull request #6
Opened 2023-03-15 18:55 UTC by Luis-ERP

Porfa este PR en particular sí dedíquenle tiempo a revisarlo y probarlo a detalle.

Es necesario hacer `npm install` para correrse.

Credenciales usadas para pruebas
email: cesarindominus@gmail.com
password: contra123

**Flujo general login**
1. user clicks submit 
2. post request /admin/auth/login  
3. store token in in LocalStorage
4. fetch GET admin data /admin/:id, the id is parsed from token
5. store admin data in LocalStorage
6. redirect to homepage

**Flujo general para checar si usuario esta autenticado**
1. user enter url in browser, ex. / 
2. check if user is authenticated
2.1. check for token and user data are stores in LocalStorage
2.2 if both id's are the same isAuthenticated returns true, else returns false
3. if authenticated, render requested page
4. if not authenticated, render login page

2023-03-15 19:56 UTC, CesarJimenezVilleda02 commented
Por que vuelves a hacer una peticion para obtener los datos del admin si el body que responde el sign in ya trae sus datos?

2023-03-15 20:15 UTC, felix-rojas commented on src/screens/login.js
> +    const handleSubmit = (e) => {
En mis pruebas[ puedes regresar al login después de hacer login y seguir pidiendo tokens al back end](https://www.notion.so/Pruebas-de-login-1201538570504a038075c13692a51186?pvs=4). 
¿tal vez un check del token local antes de enviar el post?

2023-03-15 20:45 UTC, Luis-ERP commented on src/screens/login.js
> +    const handleSubmit = (e) => {
Me parece

2023-03-15 20:47 UTC, Luis-ERP commented
> Por que vuelves a hacer una peticion para obtener los datos del admin si el body que responde el sign in ya trae sus datos?

Mmmm en la pruebas que hice del endpoint solo recuerdo haber visto el token pero deja checo de nuevo

2023-03-16 06:21 UTC, CesarJimenezVilleda02 requested changes

2023-03-16 06:21 UTC, CesarJimenezVilleda02 commented on src/client/admin.js
> +import { objectToUrlQueryString } from '../utils/dataFormat';
Muy util, gracias por la adicion, considera que queries como `{{URL}}api/v1/tours?difficulty=easy&price[lte]=1500&duration[lt]=5&sort=-ratingsAverage,price&limit=4&fields=name&fields=price,name,ratingsAverage` son validas, en estas lte significa lesss than or equal y son aceptadas por la implementacion de API features en el back

2023-03-16 06:21 UTC, CesarJimenezVilleda02 commented on src/client/authentication.js
> +const baseApiEndpoint = 'https://us-central1-robertoruiz-eca78.cloudfunctions.net/api/v1';
Por que no se movio esto a variables de entorno?

2023-03-16 06:21 UTC, CesarJimenezVilleda02 commented on src/client/authentication.js
Veo que se han agregado nuevos directorios, podrias documentarlos en el diagrama de estructura que esta en la entrega del sprint 1?

2023-03-16 06:21 UTC, CesarJimenezVilleda02 commented on src/index.js
> +export const routes = [
Esto deberiamos moverlo a un archivo aparte

2023-03-16 06:21 UTC, CesarJimenezVilleda02 commented on src/screens/login.js
> +        .then(data => {
De preferencia hay que usar Try Catch

2023-03-16 15:20 UTC, FerT99 approved these changes

2023-03-16 15:47 UTC, jorgeCastro-CVJJ approved these changes

2023-03-16 16:35 UTC, Luis-ERP commented
@felix-rojas lo que hice fue hacer que si ya esta autenticado y se va a login, lo redirija a home

2023-03-21 18:14 UTC, CesarJimenezVilleda02 approved these changes

2023-03-21 18:14 UTC, merged